vich_uploader:
    db_driver: orm

    mappings:
        cv_file:
            uri_prefix: '%cv_file%'
            upload_destination: '%kernel.project_dir%/public%cv_file%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        # blogpost_images:
        #     uri_prefix: '%blogpost_images%'
        #     upload_destination: '%kernel.project_dir%/public%blogpost_images%'
        #     namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        #     delete_on_update: true
        #     delete_on_remove: true
        # profile_picture:
        #     uri_prefix: '%profile_picture%'
        #     upload_destination: '%kernel.project_dir%/public%profile_picture%'
        #     namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        #     delete_on_update: true
        #     delete_on_remove: true